bitbucket:
  name: https://github.com/CodeBlueLabs/sampleproduct-1-services.git
  username: OneDigitalAdmin
  password: pass1234
  branch: master

pws:
  url: https://api.run.pivotal.io
  username: onedigitaladmin@cognizant.com
  password: Pass123$
  organization: Autoloan
  space: PALImmersion
  webappurl: https://palimmersionapp.cfapps.io/
slack:
  repository: cfcommunity/slack-notification-resource
  tag: latest
  url: https://hooks.slack.com/services/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
  channel: "#buildroom"
domain:
  name: pcfalm.agileinteractivelab.com
sonar:
  repository:
    name: dmasilamani/sonar-quality-gate
    tag: latest
  url: http://sonar.cognizantagilelab.com/
  authtoken: 9ca75f4e0a4afeb535d872ab5ee9dedb9458499e
  projectkey: PALIMMERSION
  projectname: SampleProduct-1
  sources: src/main/java/com/cognizant
project:
  version: 1.0.0
environment:
  testresult:
    username: admin
    password: "@g1l3xp"
    url: http://cognizantagilelab.com/manager/text
  tomcat:
    username: admin
    password: "@g1l3xp"
    url: https://futureofit.cognizant.com/manager/text
app:
  url: http://sampleproduct1-ws.cfapps.io/
  unittest: 
    url: http://cognizantagilelab.com/sampleproduct1test
    name: sampleproduct1test
